config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show, :update, :new, :edit, :create, :destroy] do
    resources :queue_estimations, only: [:new, :create]
  end
  patch '/event_wishlist', to: "event_wishlists#update", as: :event_wishlist

  resources :queue_estimations, only: [:index, :show, :destroy]
  resources :follows, only: [:destroy, :create]

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get '/tagged', to: "events#tagged", as: :tagged
  get '/dashboard', to: "pages#dashboard", as: :dashboard
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">

     <%= link_to root_path do %>
     <i class="button fas fa-home"></i>
    <% end %>

    <%= link_to events_path do %>
   <i class="button fas fa-list-ul"></i>
    <% end %>

  <%= link_to dashboard_path do %>
    <i class="button fab fa-gratipay"></i>
  <% end %>

<%= link_to new_event_path do %>
   <i class="button fas fa-plus-circle"></i>
    <% end %>
  </div>
</div>
<!--
   <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a> -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-w.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="fas fa-cog"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <span data-toggle="dropdown" id="navbarDropdown" aria-haspopup="true" aria-expanded="false"><%=current_user.nickname %></span>
        </li>
        <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "underline" %>
            <%=current_user.email %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>