config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show, :update, :new, :edit, :create, :destroy] do
    resources :queue_estimations, only: [:new, :create]
  end
  patch '/event_wishlist', to: "event_wishlists#update", as: :event_wishlist

  resources :queue_estimations, only: [:index, :show, :destroy]
  resources :follows, only: [:destroy, :create]

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get '/tagged', to: "events#tagged", as: :tagged
  get '/dashboard', to: "pages#dashboard", as: :dashboard
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_many :queue_estimations, dependent: :destroy
  has_one :chatroom, dependent: :destroy
  has_one_attached :photo
  acts_as_taggable_on :tags
  acts_as_taggable_on :genre, :size, :place
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :event_wishlists, dependent: :destroy

  def self.create_from_scraping(events)
    events.each do |event_info|
      event_seed = Event.create!(event_info)
      Chatroom.create!({ name: "Clubchat", event_id: event_seed.id })
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.order(:start_time)
    @events = policy_scope(Event).geocoded

    if params[:query_word].present?
      sql_query = "title ILIKE :query OR description ILIKE :query OR location ILIKE :query OR line_up ILIKE :query"
      @events = @events.where(sql_query, query: "%#{params[:query_word]}%")
    end

    if params[:event_date].present?
      @events = @events.select { |event| event.start_time == params[:event_date] }
    end
    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: event })
      }
    end
  end

  def show
    @favorite_exists = EventWishlist.where(event: @event, user: current_user).length > 0
    set_event
    @user = @event.user
    @related_events = @event.find_related_tags
    @chatroom = @event.chatroom
    @message = Message.new
    @last_queues = @event.queue_estimations.last(3)
    @very_last_queues = @event.queue_estimations.last(1)
  end

  def edit
    set_event
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      @event.create_chatroom!(name: "Clubchat")
      redirect_to event_path(@event)
    else
      render :new
    end
    authorize @event
  end

  def update
    set_event
    if @event.update(event_params)
      redirect_to @event, notice: "#{@event.title} was succesfully updated"
    else
      render :new
    end
  end

  def destroy
    set_event
    if @event.destroy
      flash[:notice] = "\"#{@event.title}\" was successfully deleted."
      redirect_to events_path
    else
      flash.now[:alert] = "There was an error deleting the event."
      render :show
    end
  end

  def tagged
    if params[:tag].present?
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end
  end

  # def self.search(search)
  #   if search
  #     events = Event.all
  #     events = events.where(start_time: search[:":start_time"][","])
  #     return events
  #   else
  #     Event.all
  #   end
  # end

  private

  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:title, :description, :category, :start_time, :end_time, :address, :price, :line_up, :location, :photo, :tag_list)
  end
end

app/views/events/_info_window.html.erb
<div class=marker-container>
<h5><%= event.title %></h5>
<h6><i class="fas fa-capsules"></i>&nbsp;&nbsp;<%= event.location %> on <%=event.start_time.strftime("%d %b %y")%></h6>
<p><i class="fas fa-compass"></i>&nbsp;&nbsp;<%= event.address %></p>
</div>

app/views/events/edit.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <body>
      <div class="login-box">
        <h2>Add Your Event</h2>
          <form>
            <div class="user-box">
              <%= f.input :title %>
            </div>
             <div class="user-box">
              <%= f.input :location %>
            </div>
            <div class="user-box">
               <%= f.input :address, id: "event_address"%>
            </div>
            <div class="user-box">
              <%= f.input :category %>
            </div>
              <div class="user-box">
              <%= f.input :line_up %>
            </div>
            <div class="user-box">
              <%= f.input :description %>
            </div>
            <div class="user-box">
              <%= f.input :price %>
            </div>
            <div class="user-box">
              <%= f.input :start_time%>
            </div>
            <div class="user-box">
              <%= f.input :end_time%>
            </div>
            <div class="user-box">
              <%=  f.input :photo, as: :file  %>
            </div>
            <div class="form-actions">
              <%= f.button :submit%>
            </div>
          </form>
        </div>
  </body>
<% end %>

app/views/events/index.html.erb
<% content_for :meta_title, "Discover all types of events around your position in one click" %>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.js"></script>
<div class=media-display-home>
<link
rel="stylesheet"
href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.css"
type="text/css"
/>
<div class=media-map-container>
<div
  id="map"
  style="width: 100vw; height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<button id="itinary" class="btn btn-default" style="z-index: 10000; position: absolute; padding: 0; border: none; top: 48px; right: 8px;"><i class="fas fa-directions fa-2x"></i></button>
</div>
<div class="container indexbackground" style="top: 50vh; ">

  <div id="touch" draggable>
    <div class="drag-bar">

    </div>
  </div>

    <div class="search-form-home">
      <%= form_tag events_path, method: :get do %>
      <div class="d-flex justify-items-center align-items-center">
        <div class="search-form-control">
          <%= text_field_tag :query_word,
          params[:query_word],
          class: "form-control",
            placeholder: "Type"
            %>
          </div>
          <div class="date-filter-box">
            <%= date_field_tag :event_date, id: "date_id" %></div>
<!--      <input type="date" name="event_date" placeholder="pick a date">
-->        <div class="btn-search">
             <%= submit_tag "Search", class: "btn btn-sm btn-outline-secondary" %>
          </div>

      <!--   <button type="button" class="btn"><i class="fas fa-search"></i></button>
      </div> -->
    </div>
    <% end %>
  </div>

    <% @events.each do |event| %>

    <div class="card-product card-index position-relative">
      <% favorite_exists = EventWishlist.where(event: event, user: current_user).length > 0 %>


        <div style="display: none" id="favorite_link">
         <%= link_to @favorite_text, event_wishlist_path(event: event), method: :patch, data: {favorite: favorite_exists}, remote: true %>
        </div>
        <div class="text-center" id="heart" style="color: white">
         <% if favorite_exists %>
            <i class="fas fa-heart fa-lg"></i>
          <% else %>
            <i class="far fa-heart"></i>
          <% end %>
        </div>
       <% if event.photo.attached? %>
      <div class="event-left-image"><%= cl_image_tag event.photo.key, crop: :fit %></div>
      <% else %>
      <img src= <%= event.photo_link %> />
      <% end %>

      <div class="card-product-infos">
        <%= link_to event_path(event) do %>
        <h3><%=event.start_time.strftime("%d/%m/%Y")%></h3>
        <p style="margin-right: 30px;"><strong><%=event.title %></strong> at <%=event.location%></p>
          <% end %>
        </div>
      </div>
    <% end %>

</div>
  </div>

app/views/events/new.html.erb
<% content_for :meta_title, "Add your own event and share it with everyone!" %>
<div class="form container">

<%= simple_form_for(@event) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="login-box">
    <h2>Add Your Event</h2>
    <form>
      <div class="user-box">
        <%= f.input :title %>
      </div>
      <div class="user-box">
        <%= f.input :location %>
      </div>
      <div class="user-box">
       <%= f.input :address, id: "event_address"%>
     </div>
    <!--  <div class="user-box">
      <%= f.input :category %>
    </div> -->
    <div class="user-box">
      <%= f.input :line_up %>
    </div>
    <div class="user-box">
      <%= f.input :description %>
    </div>
<!--     <div class="user-box">
      <%= f.input :tag_list %>
    </div> -->
   <!--  <div class="user-box">
      <%= f.input :price %>
    </div> -->
    <div class="user-box">
      <%= f.input :start_time%>
    </div>
    <div class="user-box">
      <%= f.input :end_time%>
    </div>
    <div class="user-box">
      <%=  f.input :photo, as: :file  %>
    </div>
    <div class="form-actions">
      <%= f.button :submit%>
    </div>
  </form>
</div>
<% end %>

</div>

app/views/events/show.html.erb
<% content_for :meta_title, "Find all the relevant informations you need before going to this event." %>
<div class=media-display-show>
<div class="img-container">
  <% if @event.photo.attached? %>
  <div class="seed-img">
    <%= cl_image_tag @event.photo.key, crop: :fit %>
  </div>
  <% else %>
  <div class="seed-img"><img src="<%= @event.photo_link %>" alt="" /></div>
  <% end %>
</div>

<% @very_last_queues.each do |very_last_queue| %>
  <% if very_last_queue.waiting_time < 30 %>
     <div class="card-q">
  <div class="card-q-min text-center">
    <h2><i class="far fa-pause-circle"></i> Queue estimation</h2>
  </div>
  <div class="card-q-infos text-center">
  <h2><%= very_last_queue.waiting_time %>min</h2>
  </div>
</div>
<% elsif very_last_queue.waiting_time > 60 %>
<div class="card-q-l">
  <div class="card-q-min text-center">
    <h2><i class="far fa-pause-circle"></i> Queue estimation</h2>
  </div>
  <div class="card-q-infos text-center">
  <h2><%= very_last_queue.waiting_time %>min</h2>
  </div>
</div>
<% else %>
<div class="card-q-ll">
  <div class="card-q-min text-center">
    <h2><i class="far fa-pause-circle"></i> Queue estimation</h2>
  </div>
  <div class="card-q-infos text-center">
  <h2><%= very_last_queue.waiting_time %>min</h2>
  </div>
</div>
  <% end %>
<% end %>
<!-- <div class="title">
    <h1><%= @event.title %></h1>
</div> -->
<div class="card-i">


  <div class="card-i-l text-center">
    <h2><i class="fas fa-warehouse"></i>&nbsp;&nbsp;<strong> <%= @event.location %> </strong> <br><br>
    <i class="fas fa-map-marker-alt"></i>&nbsp;&nbsp;<%= @event.address %></h2>
  </div>
  <div class="card-i-infos">
    <span><%= @event.start_time.strftime("%a %d") %></span>
  </div>
</div>

<div class="card-line">
  <div class="card-line-l">
    <h2>LINE-UP</h2>
  </div>
  <div class="card-line-infos text-center">
    <span><%= @event.line_up %></span>
  </div>
</div>
<div id="accordion">
  <div class="card-d">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0 text-center">
        <button class="btn-desc text-center" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <p class="descripbtn">Click to read the description</p>
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
      <p><%= @event.description %></p></div>
    </div>
  </div>
  </div>

  <div class="qest text-center">
    <h2>Already in front of the club?</h2>
    <%= link_to new_event_queue_estimation_path(@event,
    @queue_estimation) do %>
    <button type="button" class="queue-btn btn btn-secondary ">Give a estimation of the queue
    </button>
    <% end %>
  </div>
  <br>
<br>
  <div id=chatrooomi>
    <h1>
      <%= @chatroom.name %>
    </h1>
      <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
      <% @chatroom.messages.each do |message| %>
      <div class="message-container" id="message-<%= message.id %>">
        <i class="author">
            <small>
              <strong><%= message.user.nickname %> </strong> <%= message.created_at.strftime("%w/%d/%y at %l:%M%p") %></small>
            </i>
            <p>
              <%= message.content %>
            </p>
          </div>
          <% end %>
        </div>
        <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
        <%=
        f.input :content, label: false, placeholder: "Let's chat" %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <% end %>
      </div>

 <!--  <ul>
    <#% @related_events.each do |event| %>
    <li>
      <%#= event.title %>
      <#% end %>
    </li>
  </ul>

<div>
<#% if current_user.event_wishlists.find {|event_w| event_w.event_id =
  @event.id} %>
  <#% else %>
  <#% end %>
</div>
</div> -->

<!-- <div class="container-heart" style="position: relative; width: 100%; height: 6px, margin-top: 20px; margin-bottom: 50px">

 <div style="display: none" id="favorite_link">
    <#%= link_to @favorite_text, event_wishlist_path(event: @event), method: :patch, id: "favorite_link", data: {favorite: @favorite_exists}, remote: true %>
  </div>

  <div class="text-center heartshow" id="heart" style="color: white">
   <#% if @favorite_exits %>
      <i class="fas fa-heart-broken fa-lg"></i>
    <#% else %>
      <i class="fas fa-heart fa-lg"></i>
    <#% end %>
  </div>
</div> -->

    <!-- FOLLOW PART TO IMPLEMENT LATER
 -->    <!-- <div>
  <%# if user_signed_in? && current_user != @user %>
    <%# if current_user.following?(@user) %>
    <%#= button_to  "Unfollow", follow_path(user_id: @user.id), method: :delete, class: 'btn btn-info'%>
    <%# else  %>
    <%#= button_to "Follow", follows_path(user_id: @user.id), class: 'btn btn-primary'%>
    <%# end %>
  <%# end %>
</div> -->



  <div>
    <% if policy(@event).destroy? %>
    <p>
      <%= link_to ('<i class="fas fa-trash"></i>').html_safe, event_path(@event), method: :delete, data:
      { confirm: "Are you sure?"}, class: 'btn'%>
    </p>
    <% end %>
    <% if policy(@event).edit? %>
    <p>
      <%= link_to ('<i class="fas fa-edit"></i>').html_safe, edit_event_path(@event), class: 'btn'%>
    </p>
    <% end %>
  </div>


<!-- TO THINK IF WE KEEP IT OR NOT
 -->
<!--   <div class="queue_est text-center">
  <h2>Queue estimation</h2>
  <%# @last_queues.each do |last_queue| %>
  <div class=qest>
    <p>Queue of <strong>
      <%#= last_queue.waiting_time %>min</strong> on
      <%#= last_queue.created_at.strftime("%a %b %e at %l:%M%p")%> indicated by
      <%#= last_queue.user.email %>.</p>
    </div>
    <%# end %>
  </div> -->