config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show, :update, :new, :edit, :create, :destroy] do
    resources :queue_estimations, only: [:new, :create]
  end
  patch '/event_wishlist', to: "event_wishlists#update", as: :event_wishlist

  resources :queue_estimations, only: [:index, :show, :destroy]
  resources :follows, only: [:destroy, :create]

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get '/tagged', to: "events#tagged", as: :tagged
  get '/dashboard', to: "pages#dashboard", as: :dashboard
end

app/views/pages/dashboard.html.erb
<h1 class="text-center p-5"> Favorited </h1>
<div class=media-display-home>
<div class="production-list__item">
  <% @event_wishlists.each do |event_wishlist|%>
   <div class="card-product card-index position-relative">
    <% favorite_exists = EventWishlist.where(event: event_wishlist.event, user: current_user).length > 0 %>
    <% if event_wishlist.event.photo.attached? %>
        <div class="event-left-image">
            <%= cl_image_tag event_wishlist.event.photo.key, crop: :fit %>
        </div>
    <% else %>
        <img class="event-left-image" src=<%=event_wishlist.event.photo_link %> />
    <% end %>
    <div style="display: none" id="favorite_link">
      <%= link_to @favorite_text, event_wishlist_path(event: event_wishlist.event), method: :patch, data: {favorite: favorite_exists}, remote: true %>
    </div>
    <div class="text-center" id="heart" style="color: white">
      <% if favorite_exists %>
        <i class="fas fa-heart fa-lg"></i>
      <% else %>
        <i class="far fa-heart"></i>
      <% end %>
    </div>
      <div class="card-product-infos card-index">
          <%= link_to event_path(event_wishlist.event) do %>
            <h3><%= event_wishlist.event.start_time.strftime("%d/%m/%Y")%></h3>
            <p style="margin-right: 30px;" ><strong><%=event_wishlist.event.title %></strong> at <%=event_wishlist.event.location%></p>
           <!--  <h2><strong><%= event_wishlist.event.title %></strong></h2>
            <h2><%= event_wishlist.event.category %></h2>
            <h2>at:  <%= event_wishlist.event.location %></h2> -->
            <p><% event_wishlist.event.tag_list.each do |tag| %>
              <%= link_to tag, tagged_path(tag: tag) %>
            <% end %>
            </p>
          <% end  %>
      </div>
    </div>
  <% end %>
<!-- <h1 class="text-center p-5"> Followed </h1>
  <#% @followings.each do |follow|%>
    <div class="card-product-infos">
    <#%= follow.email %>
    <#%= follow.nickname %>
    </div>
<#% end  %> -->
</div>
</div>

app/views/pages/home.html.erb
<% content_for :meta_title, "You want to find a cool event and avoid queuing? Well, this is where you belong." %>
<div class=media-display-home>
<div class="card-category">
  <div class="container">
    <div class=home-title>
      <h1>MORGEN IST DIE FRAGE</h1>
      </div>

<!-- <form class="form-inline d-flex justify-content-center md-form form-sm">
  <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search for an event, club, or city"
    aria-label="Search">
  <i class="fas fa-search" aria-hidden="true"></i>
</form> -->

</div>
</div>
<div class="search-form-control">
  <%= form_tag events_path, id: "home-page-search", method: :get do %>
  <%= text_field_tag :query_word,
  params[:query_word],
  class: "form-control",
    placeholder: "Type a city, event, or club"
    %>
    <button type="submit" form="home-page-search" class="btn home-btn"><i class="fas fa-search"></i></button>

</div>

  <% end %>
<div class="card-product">
  <img src="https://source.unsplash.com/SbPUMwGYzLo" >
  <div class="card-product-infos">
    <h2>FIND</h2>
    <p>All types of events happening around your position</p>
  </div>
</div>

<div class="card-product">
  <img src="https://source.unsplash.com/R25Q-pAUeY8" >
  <div class="card-product-infos">
    <h2>CHECK</h2>
    <p>The live queueing time at the event and head out</p>
  </div>
</div>
<div class="card-product">
  <img src="https://source.unsplash.com/m41k1lTzjVM" >
  <div class="card-product-infos">
    <h2>SHARE</h2>
    <p>information about the queue once you arrive and party</p>
  </div>
</div>
</div>
<div class=legal-mentions>
<p><i class="far fa-copyright"></i> Q-LESS 2020, All rights reserved</p>
</div>